heartbeat.monitors:

#Monitor the Elasticsearch instance.
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://elasticsearch:9200"]
  username: '${ELASTICSEARCH_USER}'
  password: '${ELASTICSEARCH_PASSWORD}'
  name: Elasticsearch
  id: elasticsearch-monitor
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  check.request:
    method: "GET"
  check.response.status: [200]


#Monitor the Kibana instance.
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://kibana:5601"]
  username: '${ELASTICSEARCH_USER}'
  password: '${ELASTICSEARCH_PASSWORD}'
  name: Kibana
  id: kibana-monitor
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  check.request:
    method: "GET"
  check.response.status: [200, 302]

#Monitor the APM Server instance.
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://apm-server:8200"]
  name: APM Server
  id: apm-server-monitor
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  check.request:
    method: "GET"
  check.response.status: [200]

processors:
- add_docker_metadata: ~

monitoring.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: ${ELASTICSEARCH_USER}
  password: ${ELASTICSEARCH_PASSWORD}


logging.to_files: false