metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

#-------------------------------- Auto discovery -------------------------------
# Auto discover allows you to detect changes in the system and spawn new modules as they happen.
metricbeat.autodiscover:
  providers:
    - type: docker
      # https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html
      hints.enabled: true

metricbeat.modules:

#------------------------------- System Module -------------------------------
- module: system
  metricsets: ["cpu", "load", "memory", "network", "process", "process_summary", "core", "diskio", "socket"]
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  period: 10s
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

- module: system
  period: 15m
  metricsets:
    - uptime

#------------------------------- Docker Module -------------------------------
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
  name: Docker module


#---------------------------- Elasticsearch Module ----------------------------
- module: elasticsearch
  metricsets: ["node", "node_stats"]     # [node, node_stats, index, index_recovery, index_summary, shard, ml_job]
  period: 10s
  hosts: ["http://elasticsearch:9200"]
  username: '${ELASTICSEARCH_USER}'
  password: '${ELASTICSEARCH_PASSWORD}'


#------------------------------- Logstash Module -------------------------------
# - module: logstash
#   metricsets: ["node", "node_stats"]
#   enabled: true
#   period: 10s
#   hosts: ["localhost:9600"]


#------------------------------- MongoDB Module -------------------------------
# - module: mongodb
#   metricsets: ["dbstats", "status", "collstats", "metrics", "replstatus"]
#   period: 10s
#   enabled: true

#   # The hosts must be passed as MongoDB URLs in the format:
#   # [mongodb://][user:pass@]host[:port].
#   # The username and password can also be set using the respective configuration
#   # options. The credentials in the URL take precedence over the username and
#   # password configuration options.
#   hosts: ["localhost:27017"]
#   # Username to use when connecting to MongoDB. Empty by default.
#   #username: user

#   # Password to use when connecting to MongoDB. Empty by default.
#   #password: pass


#================================ Processors ===================================
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_locale:
    format: offset
- add_host_metadata:
    netinfo.enabled: true

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  username: '${ELASTICSEARCH_USER}'
  password: '${ELASTICSEARCH_PASSWORD}'